replicaCount: 1

nameOverride: "engine"
fullnameOverride: "engine"

image:
  repository: qlikcore/engine
  tag: 12.424.0
  pullPolicy: IfNotPresent
  env:
    - name: TZ
      value: "America/New_York"
  args:
    AcceptEULA: "no" # change to 'yes' if you accept the Qlik Core EULA
    DocumentDirectory: /doc
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9090'
  
  ports:
    - containerPort: 9076
    - containerPort: 9090
    
volumeMounts:
  - mountPath: /core
    name: app-nfs
    subPath: core
  - name: engine-prestop-hook
    mountPath: /engine-prestop-hook
  - mountPath: /rules
    name: access-control

volumes:
  - name: engine-prestop-hook
    configMap:
      name: engine-prestop-hook
      defaultMode: 0755
  - name: app-nfs
    persistentVolumeClaim:
      claimName: nfs
  - name: access-control
    configMap:
      name: access-control

service:
  type: ClusterIP
  port: 9076

resources: 
  requests:
    memory: "2200Mi"
  limits:
    memory: "2200Mi"

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - engine
      topologyKey: "kubernetes.io/hostname"

read_engine_rules: resource._actions = {"read"}

hpa:
  minReplicas: 2
  maxReplicas: 5
  targetAverageValue: 250

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths: []
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

nodeSelector: {}
  # cloud.google.com/gke-nodepool : default-pool

tolerations: []
