kind: ConfigMap
apiVersion: v1
metadata:
  name: grafana-datasources
  namespace: default
  labels:
    app.kubernetes.io/name: grafana-datasources
    helm.sh/chart: {{ include "grafana.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  prometheus.yaml: |
    apiVersion: 1

    deleteDatasources:
      - name: Prometheus
        orgId: 1

    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus.default.svc:9090
      isDefault: true
      version: 1
      editable: true
