apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: engine
  namespace: default
  labels:
    app.kubernetes.io/name: engine
    helm.sh/chart: {{ include "engine.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: engine
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: Pods
    pods:
      metricName: qix_active_sessions
      targetAverageValue: {{ .Values.hpa.targetAverageValue }}
  