apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "custom-metrics-apiserver.fullname" . }}
  namespace: default
  labels:
    app.kubernetes.io/name: {{ include "custom-metrics-apiserver.name" . }}
    helm.sh/chart: {{ include "custom-metrics-apiserver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "custom-metrics-apiserver.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "custom-metrics-apiserver.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "custom-metrics-apiserver.name" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
          {{- toYaml .Values.image.args | nindent 10 }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          securityContext:
            runAsUser: 0
          volumeMounts:
          {{- toYaml .Values.image.volumeMounts | nindent 10 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      {{- toYaml .Values.image.volumes | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}