# Default values for prometheus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: prom/prometheus
  tag: v2.1.0
  pullPolicy: Always
  port: 9090
  env:
    - name: TZ
      value: "America/New_York"
  volumeMounts:
    - mountPath: /etc/prometheus/prometheus.yml
      name: prometheus-config
      subPath: prometheus.yml
      
volumes:
  - name: prometheus-config
    configMap:
      name: prometheus-config
      items:
        - key: prometheus.yml
          path: prometheus.yml
          mode: 0644

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 9090

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths: []
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  requests:
    memory: "2500Mi"
  limits:
    memory: "2500Mi"

nodeSelector: {}

tolerations: []

affinity: {}
