# Default values for qix-session.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: qlikcore/qix-session-placement-service
  tag: 0.0.1-406
  pullPolicy: IfNotPresent
  env:
    - name: TZ
      value: "America/New_York"
    - name: SESSIONS_PER_ENGINE_THRESHOLD
      value: "500"
    - name: SESSION_STRATEGY
      value: "weighted"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 9455

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths: []
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  requests:
    memory: "100Mi"
  limits:
    memory: "100Mi"

nodeSelector: {}

tolerations: []

affinity: {}
