{{- if .Values.persistence.internalStorageClass.enabled -}}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .Values.persistence.storageClass }}
{{ toYaml .Values.persistence.internalStorageClass.definition }}
{{- end }}